#%RAML 1.0
title: ePAYE
version: 1.0
protocols: [ HTTPS ]
baseUri: http://api.service.hmrc.gov.uk
mediaType: [ application/json, application/hal+json ]

documentation:
  - title: Overview
    content: !include documentation/overview.md
  - title: Data availability
    content: !include documentation/data-availability.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
  - title: Testing the API
    content: !include documentation/testing-approach.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

types:
  ChargeType:
    pattern: "[a-zA-Z0-9]+"
  ExportId:
    pattern: "[a-zA-Z0-9]+"
  EmpRef:
    pattern: "[a-zA-Z0-9]{3}/[a-zA-Z0-9]{7}"

/epaye:
  /:
    get:
      is: [ headers.acceptHeader ]
      displayName: Get access to ePAYE data
      description: This resource is the entry point to the ePAYE API. It will return a set of URLs, allowing you to access ePAYE data for each account. This will include the employer's ePAYE balance, monthly totals of RTI charges, non-RTI charges and a breakdown of individual charges.
      (annotations.scope): "read:epaye"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:epaye" ] } ]
      responses:
        200:
          body:
            application/json:
              type: !include schemas/Epaye.get.schema.array.json
              example: !include examples/Epaye.get.array.json
        401:
          body:
            application/json:
              type: !include schemas/ErrorCodes.schema.json
              examples:
                notOpenStatus:
                  description: You don't currently have an ePAYE enrolment on this account.
                  value: |
                    {
                      "code" : "INSUFFICIENT_ENROLMENTS",
                      "message" : "You are not currently enrolled for ePAYE"
                    }
  /{empRef}/total:
    uriParameters:
      empRef:
        description: A unique identifier made up of tax office number and tax office reference.
        type: string
        example: 111/A222222
    get:
      is: [ headers.acceptHeader ]
      displayName: Get ePAYE total balance
      description: This resource returns the total balance including interest on your ePAYE account.
      (annotations.scope): "read:epaye"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:epaye" ] } ]
      responses:
        200:
          body:
            application/json:
              type: !include schemas/Totals.get.schema.json
              example: !include examples/Totals.get.json
        401:
          body:
            application/json:
              type: !include schemas/ErrorCodes.schema.json
              examples:
                notOpenStatus:
                  description: You don't currently have an ePAYE enrolment on this account.
                  value: |
                    {
                      "code" : "INVALID_EMPREF",
                      "message" : "Provided EmpRef is not associated with your account"
                    }
